#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# merge in defaults and keymaps

# if [ -f $sysmodmap ]; then
#     xmodmap $sysmodmap
# fi

setxkbmap -layout us -variant intl

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# start gnome keyrings daemon
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
mkdir -p "$HOME"/.local/share/keyrings

# xrandr --output DP-1 --mode 2560x1440 --rate 59.95 --left-of DP-1  
xrandr --output HDMI1 --dpi 96

# now using pywal
nitrogen --restore &
# wal -R &

# auto backup
start_backintime &
# Network Manager Applet
nm-applet --indicator &


autostart="mpd picom dunst uncluter flameshot udiskie dwmblocks"
for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

set r rate 300 50
xinput set-prop 'MX Anywhere 2S Mouse' 'libinput Natural Scrolling Enabled' 1

[ -n "$xrdbpid" ] && wait "$xrdbpid"
[ -f ~/.xprofile ] && . ~/.xprofile
exec dwm 
