#!/bin/sh

# Environment variables set everywhere
export EDITOR="nvim"
export TERMINAL="kitty"
export READER="zathura"
export BROWSER="google-chrome-stable"
export VIDEO="vlc"
export IMAGE="sxiv"
export COLORTERM="truecolor"
export OPENER="xdg-open"
export PAGER="bat"
export WM="dwm"

# XDG Paths
export XDG_CONFIG_HOME=$HOME/.config
export XDG_CACHE_HOME=$HOME/.cache
export XDG_DATA_HOME=$HOME/.local/share
export ZDOTDIR=$HOME/.config/zsh/
export FZF_DEFAULT_COMMAND='fd --hidden --follow --exclude .git --exclude .cache'

export XDG_SESSION_TYPE=x11
export GDK_BACKEND=x11
export GDK_SCALE=1
export GDK_DPI_SCALE=1
export QT_AUTO_SCREEN_SCALE_FACTOR=0
export QT_SCALE_FACTOR=1
export QT_SCREEN_SCALE_FACTORS="1;1;1"

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

# merge in defaults and keymaps

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

setxkbmap -layout us
if [ $(uname -n) == "LapTop" ]; then
    setxkbmap -layout br -variant abnt2
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY

# start gnome keyrings daemon
eval $(/usr/bin/gnome-keyring-daemon --start)
export SSH_AUTH_SOCK
mkdir -p "$HOME"/.local/share/keyrings

# configuration for single monitor on ease
# xrandr --output DP-1 --mode 2560x1440 --rate 59.95 --left-of DP-1  

# configuration for dual monitor on LapTop
# xrandr --output DP3 --mode 2560x1440 --rate 60
if [ $(uname -n) == "LapTop" ]; then
    xrandr --output eDP-1 --mode 1280x800
    if [ -n "$(xrandr --listactivemonitors | grep "1:")" ];then
        xrandr --output DP-1  --left-of eDP-1
    fi
else
    xrandr --output DP-1
fi
nitrogen --restore &
# now using pywal
# wal -R &

# auto backup
# start_backintime &
# Network Manager Applet
nm-applet --indicator &


autostart="mpd picom dunst uncluter flameshot udiskie" #    dwmblocks"
for program in $autostart; do
	pidof -s "$program" || setsid -f "$program"
done >/dev/null 2>&1

set r rate 300 50

 . ~/.local/bin/rev


