        → julia.NumThreads                                default: null
        → julia.additionalArgs                            default: []
        → julia.cellDelimiters                            default: ["^##(?!#)","^#(\\s?)%%","^#-"]
        → julia.completionmode                            default: "qualify"
        → julia.debuggerDefaultCompiled                   default: ["Base.","-Base.!","-Base.all","-Base.all!","-Base.any","-Base.any!","-Base.cd","-Base.iterate","-Base.collect","-Base.collect_similar","-Base._collect","-Base.collect_to!","-Base.collect_to_with_first!","-Base.filter","-Base.filter!","-Base.foreach","-Base.findall","-Base.findfirst","-Base.findlast","-Base.findnext","-Base.findprev","-Base.Generator","-Base.map","-Base.map!","-Base.maximum!","-Base.minimum!","-Base.mktemp","-Base.mktempdir","-Base.open","-Base.prod!","-Base.redirect_stderr","-Base.redirect_stdin","-Base.redirect_stdout","-Base.reenable_sigint","-Base.setindex!","-Base.setprecision","-Base.setrounding","-Base.show","-Base.sprint","-Base.sum","-Base.sum!","-Base.task_local_storage","-Base.timedwait","-Base.withenv","-Base.Broadcast","Core","Core.Compiler.","Core.IR","Core.Intrinsics","DelimitedFiles","Distributed","LinearAlgebra.","Serialization","Statistics","-Statistics.mean","SparseArrays","Mmap"]
        → julia.deleteJuliaCovFiles                       default: "true"
        → julia.editor                                    default: null
        → julia.enableCrashReporter                       default: null
        → julia.enableTelemetry                           default: null
        → julia.environmentPath                           default: null
        → julia.executablePath                            default: ""
        → julia.execution.codeInREPL                      default: false
        → julia.execution.inlineResults.colors            default: {}
        → julia.execution.resultType                      default: "both"
        → julia.execution.saveOnEval                      default: false
        → julia.focusPlotNavigator                        default: false
        → julia.lint.call                                 default: true
        → julia.lint.constif                              default: true
        → julia.lint.datadecl                             default: true
        → julia.lint.disabledDirs                         default: ["docs","test"]
        → julia.lint.iter                                 default: true
        → julia.lint.lazy                                 default: true
        → julia.lint.missingrefs                          default: "none"
        → julia.lint.modname                              default: true
        → julia.lint.nothingcomp                          default: true
        → julia.lint.pirates                              default: true
        → julia.lint.run                                  default: true
        → julia.lint.typeparam                            default: true
        → julia.lint.useoffuncargs                        default: true
        → julia.liveTestFile                              default: "test\/runtests.jl"
        → julia.packageServer                             default: ""
        → julia.persistentSession.enabled                 default: false
        → julia.persistentSession.shell                   default: "\/bin\/sh"
        → julia.persistentSession.shellExecutionArgument  default: "-c"
        → julia.persistentSession.tmuxSessionName         default: "julia_vscode"
        → julia.persistentSession.warnOnKill              default: true
        → julia.plots.path                               
        → julia.runtimeCompletions                        default: false
        → julia.showRuntimeDiagnostics                    default: true
        → julia.symbolCacheDownload                       default: null
        → julia.symbolserverUpstream                      default: "https:\/\/www.julia-vscode.org\/symbolcache"
        → julia.trace.server                              default: "off"
        → julia.useCustomSysimage                         default: false
        → julia.usePlotPane                               default: true
        → julia.useProgressFrontend                       default: true
        → julia.useRevise                                 default: true

