#!/bin/bash

# Initialize swww-daemon if not running
if ! pidof swww-daemon >/dev/null; then
	swww-daemon
fi

# Retrieve monitor information
monitor_info=$(hyprctl monitors -j)
monitor_names=($(echo "$monitor_info" | jq -r '.[].name'))

# Find the main monitor (ID=0 in this case)
monitor_main=$(echo "$monitor_info" | jq -r '.[] | select(.id == 0) | .name')
echo "Main monitor is $monitor_main"

# Display images based on monitor names
for name in "${monitor_names[@]}"; do
	if [ "$name" == "$monitor_main" ]; then
		swww img "$1" --transition-type simple --transition-step 255 -o $monitor_main
	else
		swww img "$2" --transition-type simple --transition-step 255 -o $name
	fi
done
