return {
    { -- this overwrite default opts
        "nvim-treesitter/nvim-treesitter",
        opts = {
            ensure_installed = {
                "bash",
                "bibtex",
                "c",
                "cmake",
                "comment",
                "cpp",
                "dockerfile",
                "help",
                "html",
                "javascript",
                "json",
                "json5",
                "julia",
                "latex",
                "lua",
                "luap",
                "make",
                "markdown",
                "markdown_inline",
                "matlab",
                "python",
                "regex",
                "query",
                "regex",
                "sql",
                "toml",
                "tsx",
                "typescript",
                "vim",
                "yaml",
            },
            highlight = { enable = true, disable = { "swayconfig" } },
            indent = { enable = true, disable = { "swayconfig" } },
            context_commentstring = { enable = true, enable_autocmd = false },
            incremental_selection = {
                enable = true,
                disable = { "swayconfig" },
                keymaps = {
                    init_selection = "gnn", -- set to `false` to disable one of the mappings
                    node_incremental = "grn",
                    scope_incremental = "grc",
                    node_decremental = "grm",
                },
            },
        },
    },
}
