#!/usr/bin/env zsh

o_src=(-s "$HOME/Projetos/Cientista-Chefe/")
o_dst=(-t "192.168.15.63:~/Projetos/Cientista-Chefe/")
o_options=(-o "rvltD")
o_excl=(-e "$HOME/.local/share/rsync/to_exclude")
o_del=("")
o_v=("")
o_n=("")
o_b=("")
o_help=("")


# -K (keep) allows defining defaults
# h = o_help means h=(-h)
# $k get the status of zparseopts

zparseopts -K -F -- s:=o_src t:=o_dst o:=o_options d=o_del v=o_v n=o_n b=o_b h=o_help
echo $o_v
if [[ $? != 0 || "$o_help" != "" ]]; then
    echo $0
    echo Usage: $(basename "$0") "[-o options] [-d delete] [-e exclude-from] [-s source] [-t target] [-b (backwards)]"
else
    src=$o_src[2]
    tgt=$o_dst[2]
    opts="-"$o_options[2]
    excl=$o_excl[2]
    dlt=$o_del[2]
    if [[ $o_del != "" ]]; then
        dlt="--delete"
    fi
    if [[ $o_b != "" ]]; then
        aux=$src
        src=$tgt
        tgt=$aux
    fi
    if [[ $o_n != "" ]]; then
        echo " dry run "
        opts=$opts"n"
        echo $opts
    fi

    echo "rsync $opts $dlt --exclude-from=$excl $src $tgt"
    if [[ $o_v != "" ]]; then
        rsync $opts $dlt --exclude-from=$excl $src $tgt > tt
        bat -f --paging=always  tt
    else
        rsync $opts $dlt --exclude-from=$excl $src $tgt
    fi
    rm -f tt
fi


# echo "source:" > tt
# exa -l  $src | cat >> tt
# echo "destination" >> tt
# exa -l  $src | cat >> tt
# echo "excludes" >> tt
# cat $excludef >> tt
# echo "rsync -$option $delete $src $dest" >> tt 
# rsync -$option $src $dest >> tt

# if [ $v == "y" ]; then
#     bat -f --paging=always  tt
# fi
# rm tt
