#!/bin/sh

alias g='lazygit'
alias nvimrc='nvim ~/.config/nvim/lua/user/'
alias fishrc='nvim ~/.config/fish/config.fish'
alias bspwmrc='nvim ~/.config/bspwm/bspwmrc'
alias polybarrc='nvim ~/.config/polybar/config.ini'
alias picomrc='nvim ~/.config/picom/picom.conf'
alias xkbrc='nvim ~/.config/sxhkd/sxhkdrc'
alias zshrc='nvim ~/.config/zsh'
alias dwmrc='nvim ~/.config/dwm'

alias lfrc='nvim ~/.config/lf/lfrc'
alias lf='~/.local/bin/lfrun'
alias fgrep='fgrep --color=auto'


alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"


# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrorb="sudo reflector -c Brazil -f 10 -l 10 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Remarkable
alias @ease='ssh 192.168.15.63'
export EASE='192.168.15.63'


# confirm before overwriting something
alias mv='mv -i'
alias rm='rm -i'
# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB
# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'
# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'
alias pse='ps -ef'

# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

alias ls='exa -s name'
alias l='ls -lh'
alias ll='l -a'
alias q='exit'
alias mmv='noglob zmv -W'
if [[ $TERM == "xterm-kitty" ]]; then
  alias ssh="kitty +kitten ssh"
fi

source ${HOME}/.config/ranger/scripts/shell_automatic_cd.sh
alias rr="ranger_cd"

