#! /bin/sh


# nitrogen --restore &
# Random Photo Every Login
feh --bg-fill --randomize ~/Pictures/Wallpapers/* &
#feh --bg-fill ~/Pictures/Wallpapers/bspwm1.jpg


# Monitor Config
# xrandr --auto --output DVI-D-0 --mode 2560x1440 --left-of HDMI-0
 
# xrandr --output DP-1 --mode 2560x1440 --rate 59.95 --left-of DP-1  
xrandr --output HDMI1 --mode 1920x1080

# Network Manager Applet
nm-applet --indicator &

# Don't Randomly Turn off
xset s off
xset -dpms
xset s noblank

# Speedy keys
# xset r rate 210 40


# Compositor
picom -b

# Hide mouse when typing
# xbanish &

# Screenshots
flameshot &

# Bluetooth systray icon
# blueman-applet &
udiskie &

# remap caps to escape
setxkbmap "us,us" -variant ",intl" -option ctrl:nocaps -option 'grp:alt_shift_toggle'
# swap escape and caps
# setxkbmap -option caps:swapescape

xsetroot -cursor_name left_ptr
rato=$(xinput list --id-only 'MX Anywhere 2S Mouse')
xinput set-prop $rato 315 1 # reverse mouse

/bin/sh -c "backintime pw-cache start 2>&1 >/dev/null"


pgrep -x sxhkd > /dev/null || sxhkd &

# Status Bar
pkill polybar
$HOME/.config/polybar/polybar-wrapper.sh &


# use 'xrandr -q' or 'bspc query -M --names' to find the monitor names
bspc monitor -d 1 2 3 4 5 6 7 8 9 

bspc config window_gap          10
bspc config top_padding         0
bspc config bottom_padding      0
##Color settings
bspc config focused_border_color "#025db7"
bspc config normal_border_color "#aaaaaa"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 1

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  false

bspc config focus_follows_pointer       false
bspc config history_aware_focus         true

bspc config pointer_modifier control #mod1=left alt
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Code desktop='^2' follow=on private=on
bspc rule -a Google-chrome desktop='^3' follow=on private=on
bspc rule -a firefox desktop='^3' follow=on private=on
bspc rule -a QGIS3 desktop='^4' follow=on
bspc rule -a Gimp-2.10 desktop='^5' follow=on
bspc rule -a Inkscape desktop='^5' follow=on
bspc rule -a "Mendeley Desktop" desktop='^6' follow=on
bspc rule -a okular desktop='^9' follow=on
bspc rule -a qtws desktop='^7' follow=on
bspc rule -a "YouTube Music" desktop='^7' follow=on

bspc rule -a Eog follow=on state=floating
bspc rule -a Gthumb follow=on state=floating

bspc rule -a Matplotlib follow=on state=floating
bspc rule -a zoom follow=on state=floating
bspc rule -a vlc follow=on state=floating
bspc rule -a Pavucontrol follow=on state=floating
bspc rule -a Gnome-screenshot follow=state=floating
bspc rule -a Blueman-manager follow=on state=floating
bspc rule -a matplotlib follow=on state=floating

