#! /bin/sh


setxkbmap us -variant intl -option ctrl:nocaps
# other options wuld be ... -option grp:ctrls_toggle -option ctrl:nocaps 

nitrogen --restore &
xsetroot -cursor_name left_ptr
picom  -f &
rato=$(xinput list --id-only 'MX Anywhere 2S Mouse')
xinput set-prop $rato 315 1 # reverse mouse

/bin/sh -c "backintime pw-cache start 2>&1 >/dev/null"

pkill polybar
$HOME/.config/polybar/launch.sh &

pgrep -x sxhkd > /dev/null || sxhkd &

# use 'xrandr -q' or 'bspc query -M --names' to find the monitor names
bspc monitor -d I II III IV V VI VII VIII IX X 

bspc config window_gap          8
bspc config top_padding         0
bspc config bottom_padding      0
##Color settings
bspc config focused_border_color "#025db7"
bspc config normal_border_color "#aaaaaa"
bspc config presel_feedback_color "#1ABB9B"
bspc config border_width 1

bspc config split_ratio          0.55
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config paddingless_monocle  false

bspc config focus_follows_pointer       false
bspc config history_aware_focus         true

bspc config pointer_modifier control #mod1=left alt
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner

bspc rule -a Code desktop='^2' follow=on private=on
bspc rule -a Google-chrome desktop='^3' follow=on private=on
bspc rule -a firefox desktop='^3' follow=on private=on
bspc rule -a QGIS3 desktop='^4' follow=on
bspc rule -a Gimp-2.10 desktop='^5' follow=on
bspc rule -a Inkscape desktop='^5' follow=on
bspc rule -a "Mendeley Desktop" desktop='^6' follow=on
bspc rule -a okular desktop='^7' follow=on

bspc rule -a Eog follow=on state=floating
bspc rule -a Gthumb follow=on state=floating

bspc rule -a Matplotlib follow=on state=floating
bspc rule -a zoom follow=on state=floating
bspc rule -a vlc follow=on state=floating
bspc rule -a Pavucontrol follow=on state=floating
bspc rule -a Gnome-screenshot follow=state=floating
bspc rule -a Blueman-manager follow=on state=floating
bspc rule -a matplotlib follow=on state=floating

