
;==========================================================
;
;
;   ██████╗  ██████╗ ██╗  ██╗   ██╗██████╗  █████╗ ██████╗
;   ██╔══██╗██╔═══██╗██║  ╚██╗ ██╔╝██╔══██╗██╔══██╗██╔══██╗
;   ██████╔╝██║   ██║██║   ╚████╔╝ ██████╔╝███████║██████╔╝
;   ██╔═══╝ ██║   ██║██║    ╚██╔╝  ██╔══██╗██╔══██║██╔══██╗
;   ██║     ╚██████╔╝███████╗██║   ██████╔╝██║  ██║██║  ██║
;   ╚═╝      ╚═════╝ ╚══════╝╚═╝   ╚═════╝ ╚═╝  ╚═╝╚═╝  ╚═╝
;
;
;   To learn more about how to configure Polybar
;   go to https://github.com/polybar/polybar
;
;   The README contains a lot of information
;
;==========================================================

[colors]
background = #282A2E
background-alt = #3t3Br1
foreground = #C5C8C6
foreground-alt = #FFFFFF
primary = #F0C674
secondary = #8ABEB7
disabled = #707880
alert = #BD2C40
cramp1 = #55AA55
cramp2 = #F5A70A
cramp3 = #FF5555


[bar/example]
monitor = ${env:MONITOR}
enable-ipc=true
bottom = false

height = 20
width = 100%
offset-y = 0.0%
offset-x = 0.0%
radius = 0
fixed-center = true
module-margin-left = 0
module-margin-right = 0

;overline-size = 295
;overline-color = ${colors.background}
;underline-size = 2
;underline-color = ${colors.background}

padding-left = 0
padding-right = 0

border-size = 0
border-color = ${colors.foreground}

background = ${colors.background}
foreground = ${colors.foreground}
line-size = 0
font-0 = Hack Nerd Font Mono:pixelsize=11;2
font-1 = Hack Nerd Font Mono:pixelsize=16;3


modules-left = bspwm 
modules-center = xwindow 
modules-right =  running-screen bluetooth-rofi xkeyboard pulseaudio wlan date powermenu

separator =""
wm-restack = bspwm

;override-redirect = true
;scroll-up = bspwm-desknext
;scroll-down = bspwm-deskprev


cursor-click = pointer
eursor-scroll = ns-resize

[module/xkeyboard]
type = internal/xkeyboard
label-layout-foreground = ${colors.foreground}
label-layout = %name% %icon% 
layout-icon-default = :) 
layout-icon-0 = us; 
layout-icon-1 = us;
click-left =  switch

[module/pacman-updates]
type = custom/script
exec = checkupdates | wc -l
interval = 1000
label = Updates: %output%
format-foreground = ${colors.foreground}
format-background = ${colors.background}
format-prefix = "  "
format-prefix-foreground = ${colors.foreground}

[module/polybar-windows]
type = custom/script
exec = ~/.config/polybar/scripts/polybar-windows.sh 
format = <label>
format-prefix-foreground = ${colors.foreground}
label = %output%
label-padding = 1
interval = 1

[module/running-screen]
type = custom/script
exec = ~/.config/polybar/scripts/running-screen.sh
format = <label>
format-prefix-foreground = ${colors.foreground}
label = %output%
label-padding = 1
interval = 1


[module/bluetooth-rofi]
type = custom/script
exec = rofi-bluetooth --status | awk {'print $1'}
interval = 10
tail = true
label = "  "
click-left = rofi-bluetooth &

[module/bluetooth]
type = custom/script
exec = ~/.config/polybar/scripts/system-bluetooth-bluetoothctl.sh
tail = true
click-left = ~/.config/polybar/scripts/system-bluetooth-bluetoothctl.sh --toggle &



[module/xwindow]
type = internal/xwindow
label = %{T1}%title:0:30:...%%{T-}
;format = <label>
;format-foreground = ${colors.foreground}

[module/filesystem]
type = internal/fs
interval = 25

mount-0 = /

label-mounted =  %free%
label-unmounted = %mountpoint% not mounted
label-unmounted-foreground = ${colors.foreground-alt}

[module/bspwm]
type = internal/bspwm
format = <label-state><label-mode>
format-foreground = ${colors.foreground}
format-background = ${colors.background}
index-sort = false
wrapping-scroll = false
pin-workspaces = true
reverse-scroll = false

ws-icon-0 = 1;
ws-icon-1 = 2;
ws-icon-2 = 3;
ws-icon-3 = 4;
ws-icon-4 = 5;
ws-icon-5 = 6;
ws-icon-6 = 7;
ws-icon-default = " "

label-mode = %mode%
label-mode-padding = 1
label-mode-foreground = ${colors.background}
label-mode-background = ${colors.foreground}

label-focused="%{B#D8DEE9}%{F#2E3440}%{T2} %icon% %{T- F- B-}"
label-focused-foreground = ${colors.foreground}
label-focused-background = ${colors.background}
label-focused-padding = 1

label-unfocused="%{B#3B4252}%{F#D8DEE9}%{T2} %icon% %{T- F- B-}
label-unfocused-padding = 1
label-unfocused-foreground = ${colors.foreground}
label-unfocused-background = ${colors.background}
label-unfocused-underline = ${colors.background}
label-unfocused-overline = ${colors.background}

;label-visible = %icon% %name%
;label-visible-background = ${colors.background}
;label-visible-underline = ${colors.background}
;label-visible-padding = 1

label-empty = %{T2}%icon%%{T-}
label-empty-foreground = ${colors.secondary}
label-empty-padding = 1

label-occupied = %{T2}%icon%%{T-}
label-occupied-padding = 1
label-occupied-foreground = ${colors.foreground}

label-urgent = %{T2}%icon%!%{T-}
label-urgent-background = ${colors.alert}
label-urgent-padding = 1

[module/mpd]
type = internal/mpd
format-online = <label-song>  <icon-prev> <icon-stop> <toggle> <icon-next>
icon-prev = 
icon-stop = 
icon-play = 
icon-pause = 
icon-next = 
label-song-maxlen = 25
label-song-ellipsis = true

[module/xbacklight]
type = internal/xbacklight
format = <label> <bar>
label = BL
bar-width = 10
bar-indicator = |
bar-indicator-foreground = ${colors.foreground}
bar-indicator-font = 2
bar-fill = ─
bar-fill-font = 2
bar-fill-foreground = ${colors.foreground}
bar-empty = ─
bar-empty-font = 2
bar-empty-foreground = ${colors.foreground-alt}

[module/backlight-acpi]
inherit = module/xbacklight
type = internal/backlight
card = intel_backlight

[module/cpu]
type = internal/cpu
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${color.foreground}
label = %percentage:2%%

[module/memory]
type = internal/memory
interval = 2
format-prefix = " "
format-prefix-foreground = ${colors.foreground-alt}
format-underline = ${colors.foreground}
label = %gb_used%
;label = %percentage_used%%

[module/wlan]
type = internal/network
interface = wlp3s0
interval = 5.0
format-connected = <ramp-signal> <label-connected>
label-connected = %essid%
format-disconnected = _
ramp-signal-0 = "  睊"
ramp-signal-1 = "  直" 
ramp-signal-2 = "  直"
ramp-signal-3 = "   "
ramp-signal-foreground = ${colors.foreground-alt}

[module/eth]
type = internal/network
interface = eno1:warn
interval = 5.0
format-connected-underline = ${colors.foreground}
format-connected-prefix = " "
format-connected-prefix-foreground = ${colors.foreground-alt}
label-connected = %local_ip%
format-disconnected =
;format-disconnected = <label-disconnected>
;format-disconnected-underline = ${self.format-connected-underline}
;label-disconnected = %ifname% disconnected
;label-disconnected-foreground = ${colors.foreground-alt}

[module/date]
type = internal/date
interval = 5
date = %m/%d%
time =%H:%M
format-prefix-foreground = ${colors.foreground}
label = "    %date%  %time%  "

;[module/date]
;type = internal/date
;interval = 1
;date = "%A %d/%m"
;;date-alt = "%A %d-%m-%Y"
;time = "%H:%M "
;;time-alt = "%H:%M:%S "
;format-prefix = "  "
;format-prefix-foreground = ${colors.foreground} 
;format-foreground = ${colors.foreground}
;label = %date% %time%

[module/pulseaudio]
type = internal/pulseaudio
format-volume-prefix = "  "
format-volume-prefix-foreground = ${colors.foreground}
format-volume = <label-volume>
label-volume = %percentage%
label-muted = "  "
label-muted-foreground = ${colors.disabled}

[module/alsa-right]
type = internal/alsa
format-volume = <label-volume><bar-volume>
format-muted = <label-muted>
label-volume = " "
label-volume-underline = ${colors.background}
label-volume-overline = ${colors.background}
label-volume-foreground = ${color.foreground} 
format-muted-prefix =
label-muted = ""
label-muted-foreground = ${colors.primary}
bar-volume-width = 8
bar-volume-gradient = true
bar-volume-indicator = "█"
bar-volume-indicator-foreground = ${colors.background}
bar-volume-indicator-font = 0
bar-volume-fill ="█"
bar-volume-foreground-0 = ${colors.cramp1}
bar-volume-foreground-1 = ${colors.cramp1}
bar-volume-foreground-2 = ${colors.cramp1}
bar-volume-foreground-3 = ${colors.cramp1}
bar-volume-foreground-4 = ${colors.cramp1}
bar-volume-foreground-5 = ${colors.cramp2}
bar-volume-foreground-6 = ${colors.cramp2}
bar-volume-foreground-7 = ${colors.cramp3}
bar-volume-fill-font = 0
bar-volume-empty ="█"
bar-volume-empty-foreground = ${colors.foreground}
bar-volume-empty-font = 0
bar-volume-underline = ${colors.background}
bar-volume-overline = ${colors.background}

[module/alsa-left]
type = internal/alsa
format-volume = <ramp-volume>
format-muted = <label-muted>
label-volume = ""
label-volume-foreground = ${colors.foreground}
format-volume-background =${colors.background}
format-volume-foreground = ${colors.foreground}
format-muted-prefix =
label-muted = ""
label-muted-foreground = ${colors.primary}

ramp-volume-0-foreground = ${colors.foreground}
ramp-volume-1-foreground = ${colors.foreground}
ramp-volume-2-foreground = ${colors.foreground}
ramp-volume-3-foreground = ${colors.foreground}
ramp-volume-4-foreground = ${colors.foreground}
ramp-volume-5-foreground = ${colors.foreground}
ramp-volume-6-foreground = ${colors.foreground}
ramp-volume-7-foreground = ${colors.foreground}
ramp-volume-8-foreground = ${colors.foreground}
ramp-volume-9-foreground = ${colors.cramp3}

ramp-volume-0 =" "
ramp-volume-1 =" "
ramp-volume-2 =" "
ramp-volume-3 =" "
ramp-volume-4 =" "
ramp-volume-5 =" "
ramp-volume-6 =" "
ramp-volume-7 =" "
ramp-volume-8 =" "
ramp-volume-9 =" "

ramp-headphones-0 =""
ramp-headphones-1 =""


[module/temperature]
type = internal/temperature
thermal-zone = 0
warn-temperature = 60
format = <ramp> <label>
format-warn = <ramp> <label-warn>
format-warn-underline = ${self.format-underline}
label =  %temperature-c%
label-warn = %temperature-c%
label-warn-foreground = ${colors.secondary}
ramp-0 = 
ramp-1 = 
ramp-2 = 
ramp-foreground = ${colors.foreground-alt}

[module/powermenu]
type = custom/menu
expand-right = true
format-spacing = 1
label-open = "%{T2}   %{T-} " 
label-open-foreground = ${colors.alert}
label-close = "  cancel"
label-close-foreground = ${colors.alert}
label-separator = -
label-separator-foreground = ${colors.foreground}
menu-0-0-foreground=${color.alert}
menu-0-0 = reboot
menu-0-0-exec = systemctl reboot
menu-0-1 = logout
menu-0-1-exec = bspc quit
menu-0-2 = "power off "
menu-0-2-exec = systemctl poweroff

[settings]
screenchange-reload = true
;compositing-background = xor
;compositing-background = screen
;compositing-foreground = source
compositing-border = over
pseudo-transparency = false

[global/wm]
margin-top = 0
margin-bottom = 0
