#!/usr/bin/bash
TEMP=~/.config/hypr/scripts/current_wall

wallpapers=(~/.config/hypr/wallpapers/*)

config=~/.config/hypr
scripts=$config/scripts

cooldown=0.1

while true; do
	case "$1" in
	"wall")
		index=$(cat $TEMP)
		index2=$((index + 1))

		$scripts/wall "${wallpapers[$index]}" "${wallpapers[$index2]}"
		exit 0
		;;
	"cycle")
		index=$(cat $TEMP)
		index=$((index + 2))
		if [ $index -ge ${#wallpapers[@]} ]; then
			index=0
		fi
		index2=$((index + 1))
		echo $index >$TEMP
		$scripts/wall "${wallpapers[$index]}" "${wallpapers[$index2]}"
		exit 0
		;;
	"arrow-icon")
		if $scripts/toolbar_state; then
			echo ""
		else
			echo ""
		fi
		;;
	"ss-icon")
		if $scripts/toolbar_state; then
			echo ""
		else
			echo ""
		fi
		;;
	# "media")

	*)
		if $scripts/toolbar_state; then
			echo "     "
		else
			echo ""
		fi
		;;
	esac
	sleep $cooldown
done
