#!/usr/bin/bash
TEMP=/tmp/current_wall

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# waybar
# $scripts/launch_waybar &
# $scripts/launch_qshell &
# wallpaper
# expand $scripts/wall &
