#! /bin/sh
# SwayWM outputs configuration. For detailed information type "man sway"
# For a list of devices run: swaymsg -t get_outputs
# Author: Oscar Carballal Prego <oscar.carballal@protonmail.com>
# Devices
set $display_external DP-1
set $display_laptop eDP-1

output $display_laptop scale 3 pos 0 280
output $display_external pos 1280 0 mode 1920x1080@75Hz

# Disable main laptop screen
bindsym $mod+F7 output $display_laptop disable
bindsym $mod+F8 output $display_laptop enable
