#! /bin/sh
# SwayWM outputs configuration. For detailed information type "man sway"
# For a list of devices run: swaymsg -t get_outputs
# Author: Oscar Carballal Prego <oscar.carballal@protonmail.com>
# Devices
set $display_external DP-1
set $display_laptop eDP-1

output $display_laptop scale 3
output $display_external mode 1920x1080@75Hz pos 1920,0

# Default wallpaper
output * bg $wallpaper fill

# Disable main laptop screen
bindsym $mod+F7 output $display_laptop disable
bindsym $mod+F8 output $display_laptop enable
