#!/usr/bin/bash

# variables
config=$HOME/.config/hypr
scripts=$config/scripts

# notification daemon
dunst &

# waybar
$scripts/launch_waybar &

# wallpaper
# $scripts/wall $config/wallpapers/4.jpg &
waypaper --restore --backend swww

nm-applet &

# other
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP &
# notify-send -a aurora "hello $(whoami)" &
