#! /bin/sh
# SwayWM outputs configuration. For detailed information type "man sway"
# For a list of devices run: swaymsg -t get_outputs
# Author: Oscar Carballal Prego <oscar.carballal@protonmail.com>
# Devices
set $display_external HDMI-A-2

output $display_external mode 1920x1080@74.973Hz

# Default wallpaper
output * bg $wallpaper fill

# Disable main laptop screen
bindsym $mod+F7 output $display_laptop disable
bindsym $mod+F8 output $display_laptop enable
