return {
    {
        "nvim-treesitter/nvim-treesitter",
        opts = {
            ensure_installed = {
                "bibtex",
                "cmake",
                "cpp",
                "css",
                "csv",
                "fish",
                "html",
                "javascript",
                "json",
                "julia",
                "latex",
                "lua",
                "markdown",
                "markdown_inline",
                "python",
                "query",
                "regex",
                "tsx",
                "typescript",
                "vim",
                "yaml",
            },
        },
    },
}
